[package]
name = "lexer"
version = "0.1.0"
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]

[dev-dependencies]
insta.workspace = true
criterion.workspace = true

[[bench]]
name = "bench_lexer"
harness = false
